
import {
    Github,
    Linkedin,
    Mail,
    ExternalLink,
    Code2,
    Database,
    Terminal,
    Cpu,
    Monitor,
    Menu,
    X,
    FileText,
    Briefcase,
    GraduationCap,
    Laptop,
    Star,
    Check,
    Shield,
    Brain,
    MapPin,
    Phone,
    Award,
    Server,
    Layout,
    Wrench,
    Zap,
    Rocket,
    Layers,

    Folder,
    ArrowLeft,
    Download
} from "lucide-react";

export const Icons = {
    github: Github,
    linkedin: Linkedin,
    mail: Mail,
    external: ExternalLink,
    externalLink: ExternalLink,
    code: Code2,
    database: Database,
    terminal: Terminal,
    cpu: Cpu,
    monitor: Monitor,
    menu: Menu,
    close: X,
    resume: FileText,
    briefcase: Briefcase,
    education: GraduationCap,
    laptop: Laptop,
    star: Star,
    check: Check,
    shield: Shield,
    brain: Brain,
    mapPin: MapPin,
    phone: Phone,
    award: Award,
    server: Server,
    layout: Layout,
    wrench: Wrench,
    zap: Zap,
    rocket: Rocket,
    layers: Layers,
    folder: Folder,
    arrowLeft: ArrowLeft,
    download: Download
};
